/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JustificativasRouteImport } from './routes/justificativas'
import { Route as ExtratoRouteImport } from './routes/extrato'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AdminTagsRouteImport } from './routes/admin/tags'
import { Route as AdminSalasRouteImport } from './routes/admin/salas'
import { Route as AdminRelatoriosRouteImport } from './routes/admin/relatorios'
import { Route as AdminJustificativasRouteImport } from './routes/admin/justificativas'
import { Route as AdminEventosRouteImport } from './routes/admin/eventos'
import { Route as ApiPublicRfidScanRouteImport } from './routes/api/public/rfid-scan'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JustificativasRoute = JustificativasRouteImport.update({
  id: '/justificativas',
  path: '/justificativas',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtratoRoute = ExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/admin/tags',
  path: '/admin/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalasRoute = AdminSalasRouteImport.update({
  id: '/admin/salas',
  path: '/admin/salas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/admin/relatorios',
  path: '/admin/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJustificativasRoute = AdminJustificativasRouteImport.update({
  id: '/admin/justificativas',
  path: '/admin/justificativas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventosRoute = AdminEventosRouteImport.update({
  id: '/admin/eventos',
  path: '/admin/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRfidScanRoute = ApiPublicRfidScanRouteImport.update({
  id: '/api/public/rfid-scan',
  path: '/api/public/rfid-scan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/extrato': typeof ExtratoRoute
  '/justificativas': typeof JustificativasRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/justificativas': typeof AdminJustificativasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/salas': typeof AdminSalasRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/rfid-scan': typeof ApiPublicRfidScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/extrato': typeof ExtratoRoute
  '/justificativas': typeof JustificativasRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/justificativas': typeof AdminJustificativasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/salas': typeof AdminSalasRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/rfid-scan': typeof ApiPublicRfidScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/extrato': typeof ExtratoRoute
  '/justificativas': typeof JustificativasRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/justificativas': typeof AdminJustificativasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/salas': typeof AdminSalasRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/rfid-scan': typeof ApiPublicRfidScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/extrato'
    | '/justificativas'
    | '/login'
    | '/set-password'
    | '/signup'
    | '/admin/eventos'
    | '/admin/justificativas'
    | '/admin/relatorios'
    | '/admin/salas'
    | '/admin/tags'
    | '/admin/usuarios'
    | '/admin/'
    | '/api/public/rfid-scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/extrato'
    | '/justificativas'
    | '/login'
    | '/set-password'
    | '/signup'
    | '/admin/eventos'
    | '/admin/justificativas'
    | '/admin/relatorios'
    | '/admin/salas'
    | '/admin/tags'
    | '/admin/usuarios'
    | '/admin'
    | '/api/public/rfid-scan'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/extrato'
    | '/justificativas'
    | '/login'
    | '/set-password'
    | '/signup'
    | '/admin/eventos'
    | '/admin/justificativas'
    | '/admin/relatorios'
    | '/admin/salas'
    | '/admin/tags'
    | '/admin/usuarios'
    | '/admin/'
    | '/api/public/rfid-scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ExtratoRoute: typeof ExtratoRoute
  JustificativasRoute: typeof JustificativasRoute
  LoginRoute: typeof LoginRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SignupRoute: typeof SignupRoute
  AdminEventosRoute: typeof AdminEventosRoute
  AdminJustificativasRoute: typeof AdminJustificativasRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminSalasRoute: typeof AdminSalasRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicRfidScanRoute: typeof ApiPublicRfidScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/justificativas': {
      id: '/justificativas'
      path: '/justificativas'
      fullPath: '/justificativas'
      preLoaderRoute: typeof JustificativasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extrato': {
      id: '/extrato'
      path: '/extrato'
      fullPath: '/extrato'
      preLoaderRoute: typeof ExtratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/admin/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/salas': {
      id: '/admin/salas'
      path: '/admin/salas'
      fullPath: '/admin/salas'
      preLoaderRoute: typeof AdminSalasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/justificativas': {
      id: '/admin/justificativas'
      path: '/admin/justificativas'
      fullPath: '/admin/justificativas'
      preLoaderRoute: typeof AdminJustificativasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eventos': {
      id: '/admin/eventos'
      path: '/admin/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AdminEventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rfid-scan': {
      id: '/api/public/rfid-scan'
      path: '/api/public/rfid-scan'
      fullPath: '/api/public/rfid-scan'
      preLoaderRoute: typeof ApiPublicRfidScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ExtratoRoute: ExtratoRoute,
  JustificativasRoute: JustificativasRoute,
  LoginRoute: LoginRoute,
  SetPasswordRoute: SetPasswordRoute,
  SignupRoute: SignupRoute,
  AdminEventosRoute: AdminEventosRoute,
  AdminJustificativasRoute: AdminJustificativasRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminSalasRoute: AdminSalasRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicRfidScanRoute: ApiPublicRfidScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
