/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JustificativasRouteImport } from './routes/justificativas'
import { Route as ExtratoRouteImport } from './routes/extrato'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AdminTagsRouteImport } from './routes/admin/tags'
import { Route as AdminSalasRouteImport } from './routes/admin/salas'
import { Route as AdminEventosRouteImport } from './routes/admin/eventos'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JustificativasRoute = JustificativasRouteImport.update({
  id: '/justificativas',
  path: '/justificativas',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtratoRoute = ExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/admin/tags',
  path: '/admin/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalasRoute = AdminSalasRouteImport.update({
  id: '/admin/salas',
  path: '/admin/salas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventosRoute = AdminEventosRouteImport.update({
  id: '/admin/eventos',
  path: '/admin/eventos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/extrato': typeof ExtratoRoute
  '/justificativas': typeof JustificativasRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/salas': typeof AdminSalasRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/extrato': typeof ExtratoRoute
  '/justificativas': typeof JustificativasRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/salas': typeof AdminSalasRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/extrato': typeof ExtratoRoute
  '/justificativas': typeof JustificativasRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/salas': typeof AdminSalasRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/extrato'
    | '/justificativas'
    | '/login'
    | '/signup'
    | '/admin/eventos'
    | '/admin/salas'
    | '/admin/tags'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/extrato'
    | '/justificativas'
    | '/login'
    | '/signup'
    | '/admin/eventos'
    | '/admin/salas'
    | '/admin/tags'
    | '/admin/usuarios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/extrato'
    | '/justificativas'
    | '/login'
    | '/signup'
    | '/admin/eventos'
    | '/admin/salas'
    | '/admin/tags'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ExtratoRoute: typeof ExtratoRoute
  JustificativasRoute: typeof JustificativasRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AdminEventosRoute: typeof AdminEventosRoute
  AdminSalasRoute: typeof AdminSalasRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/justificativas': {
      id: '/justificativas'
      path: '/justificativas'
      fullPath: '/justificativas'
      preLoaderRoute: typeof JustificativasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extrato': {
      id: '/extrato'
      path: '/extrato'
      fullPath: '/extrato'
      preLoaderRoute: typeof ExtratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/admin/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/salas': {
      id: '/admin/salas'
      path: '/admin/salas'
      fullPath: '/admin/salas'
      preLoaderRoute: typeof AdminSalasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eventos': {
      id: '/admin/eventos'
      path: '/admin/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AdminEventosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ExtratoRoute: ExtratoRoute,
  JustificativasRoute: JustificativasRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AdminEventosRoute: AdminEventosRoute,
  AdminSalasRoute: AdminSalasRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
